name: EggHunt
version: 0.4
author: Jake (John) Moe (JakesAddress@gmail.com)
main: me.JakeMoe.EggHunt.Main
website: https://github.com/JakeMoe/EggHunt
database: false
depend: [WorldGuard]

commands:
  eh:
    description: EggHunt base command
    permission: EggHunt.eh
    permission-message: You do not have access to this command.
    usage: /eh

permissions:
  EggHunt.*:
    description: Gives access to all EggHunt commands
    default: true
    children:
      EggHunt.eh: true
  EggHunt.eh:
    description: EggHunt base command
    default: true
